services:
  - type: web
    name: weatherwise-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5009
      - key: OPENWEATHERMAP_API_KEY
        sync: false
